name: Publish to ESP Component Registry

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Upload to ESP Component Registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "XPowersLib:."
          namespace: "cube32esp"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
